# Generated by Django 4.1.2 on 2022-11-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_order_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user_mail",
        ),
    ]
