# Generated by Django 4.1.2 on 2022-11-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="feedbackmodel",
        ),
    ]
