# Generated by Django 4.1.2 on 2022-11-02 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
