# Generated by Django 4.1.2 on 2022-11-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
    ]
