# Generated by Django 4.1.2 on 2022-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_topic_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnail'),
        ),
    ]
