# Generated by Django 4.1.2 on 2022-11-08 18:51

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_delete_lessons"),
    ]

    operations = [
        migrations.CreateModel(
            name="lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lessonName", models.TextField(max_length=200, null=True)),
                (
                    "file",
                    models.FileField(
                        default="",
                        null=True,
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="courses/video",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
    ]
