# Generated by Django 4.1.2 on 2022-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_feedbackmodel_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="educator_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
