# Generated by Django 4.1.2 on 2022-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="review_count",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
