# Generated by Django 4.1.2 on 2022-11-06 17:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_feedbackmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="lesson",
            field=cloudinary.models.CloudinaryField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
