# Generated by Django 4.1.2 on 2022-10-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_lessons_thumbnail_course_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(default="", upload_to="courses/thumbnail"),
        ),
    ]
