# Generated by Django 4.1.2 on 2022-11-03 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_remove_category_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
