# Generated by Django 4.1.2 on 2022-11-02 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_review_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.PositiveIntegerField(
                default="newly hosted course",
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
