# Generated by Django 4.1.2 on 2022-11-02 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
