# Generated by Django 4.1.2 on 2022-10-29 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price_alter_course_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(999)]
            ),
        ),
    ]
