# Generated by Django 4.1.2 on 2022-11-09 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_feedbackmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodel",
            name="user",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
