# Generated by Django 4.1.2 on 2022-11-02 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
