# Generated by Django 4.1.2 on 2022-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_lessons_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="lesson",
            field=models.FileField(null=True, upload_to="courses/video"),
        ),
    ]
