# Generated by Django 4.1.2 on 2022-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_feedbackmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="length",
            field=models.IntegerField(default=0.0),
        ),
    ]
