# Generated by Django 4.1.2 on 2022-11-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_educator_name"),
        ("courses", "0007_alter_lessons_lesson"),
    ]

    operations = []
