# Generated by Django 4.1.2 on 2022-11-11 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_lessons_length"),
        ("courses", "0008_feedbackmodel_sender"),
    ]

    operations = []
