# Generated by Django 4.1.2 on 2022-11-08 08:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_merge_20221108_0809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="lesson",
            field=models.FileField(
                default="",
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="courses/video",
            ),
        ),
    ]
