# Generated by Django 4.1.2 on 2022-11-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_merge_20221111_0505"),
        ("courses", "0009_merge_20221111_0620"),
    ]

    operations = []
