# Generated by Django 4.1.2 on 2022-11-02 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_course_educator_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="latest_review",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
