# Generated by Django 4.1.3 on 2022-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_merge_20221111_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="length",
            field=models.CharField(max_length=100),
        ),
    ]
