# Generated by Django 4.1.2 on 2022-11-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_email'),
        ('courses', '0011_course_latest_review'),
    ]

    operations = [
    ]
