# Generated by Django 4.1.3 on 2022-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_alter_lessons_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="length",
            field=models.CharField(default="", max_length=100),
        ),
    ]
