# Generated by Django 4.1.3 on 2022-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_lessons_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="weighted_rating",
            field=models.FloatField(default=0),
        ),
    ]
