# Generated by Django 4.1.2 on 2022-11-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_merge_0004_category_email_0011_course_latest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Interest1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='Interest2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='Interest3',
            field=models.BooleanField(default=False),
        ),
    ]
