# Generated by Django 4.1.2 on 2022-11-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_category_interest1_category_interest2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Interest1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Interest2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Interest3',
        ),
    ]
