# Generated by Django 4.1.3 on 2022-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_feedbackmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodel",
            name="user",
            field=models.CharField(default=" ", max_length=200),
        ),
    ]
