# Generated by Django 4.1.2 on 2022-11-04 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
