# Generated by Django 4.1.2 on 2022-11-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_rating_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="rating",
            new_name="Feedback",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="category",
        ),
        migrations.AddField(
            model_name="feedback",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
