# Generated by Django 4.1.3 on 2022-11-17 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_alter_feedbackmodel_user"),
        ("courses", "0017_search"),
    ]

    operations = []
