# Generated by Django 4.1.2 on 2022-11-04 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_rename_rating_feedback_remove_feedback_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
