# Generated by Django 4.1.2 on 2022-11-04 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0018_feedback_comment_feedback_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
