# Generated by Django 4.1.2 on 2022-11-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_remove_feedback_user_feedback_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="rating",
            new_name="latest_review",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
    ]
