# Generated by Django 4.1.2 on 2022-11-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_rename_rating_feedback_latest_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="latest_review",
            new_name="rating",
        ),
    ]
