# Generated by Django 4.1.2 on 2022-11-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_rename_latest_review_feedback_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
