# Generated by Django 4.1.2 on 2022-11-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0024_feedbackmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedbackmodel",
            old_name="rating",
            new_name="latest_review",
        ),
    ]
