# Generated by Django 4.1.2 on 2022-11-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="purchased_courses",
        ),
    ]
