# Generated by Django 4.1.2 on 2022-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuserregistration',
            name='is_prime',
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
