# Generated by Django 4.1.2 on 2022-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserregistration',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
    ]
