# Generated by Django 4.1.2 on 2022-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuserregistration",
            name="wallet",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
