# Generated by Django 4.1.2 on 2022-11-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_newuserregistration_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuserregistration',
            old_name='interest',
            new_name='interested',
        ),
    ]
