# Generated by Django 4.1.2 on 2022-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_newuserregistration_is_prime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserregistration',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
