# Generated by Django 4.1.2 on 2022-10-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_newuserregistration_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuserregistration',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
