# Generated by Django 4.1.2 on 2022-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_newuserregistration_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuserregistration",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
