# Generated by Django 4.1.2 on 2022-10-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_newuserregistration_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="otp",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
