# Generated by Django 4.1.2 on 2022-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_profile_picture_newuserregistration_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserregistration',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
