# Generated by Django 4.1.2 on 2022-10-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_newuserregistration_is_prime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuserregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='newuserregistration',
            name='is_prime',
        ),
        migrations.RemoveField(
            model_name='newuserregistration',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='newuserregistration',
            name='picture',
        ),
    ]
