# Generated by Django 4.1.2 on 2022-11-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_squashed_0003_lessons"),
        ("base", "0004_newuserregistration_purchasedcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="purchasedCourse",
            field=models.ManyToManyField(to="courses.course"),
        ),
    ]
