# Generated by Django 4.1.2 on 2022-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_newuserregistration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='picture',
            field=models.ImageField(default='images/defaultProfilePicture.png', upload_to='images'),
        ),
    ]
