# Generated by Django 4.1.2 on 2022-11-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_newuserregistration_purchasedcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                default="M",
                max_length=1,
            ),
        ),
    ]
