# Generated by Django 4.1.2 on 2022-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_newuserregistration_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="dateOfBirth",
            field=models.DateField(default="2002-11-16", null=True),
        ),
    ]
