# Generated by Django 4.1.2 on 2022-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_feedbackmodel_user"),
        ("base", "0011_alter_newuserregistration_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="purchasedCourse",
            field=models.ManyToManyField(blank=True, to="courses.course"),
        ),
    ]
