# Generated by Django 4.1.2 on 2022-11-11 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_newuserregistration_purchasedcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="wallet",
            field=models.FloatField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
