# Generated by Django 4.1.3 on 2022-11-15 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_newuserregistration_educator_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuserregistration",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="verifyEmail",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email address",
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="user_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, unique=True
            ),
        ),
    ]
