# Generated by Django 4.1.3 on 2022-11-15 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_newuserregistration_educator_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuserregistration",
            name="is_certified_educator",
        ),
    ]
