# Generated by Django 4.1.3 on 2022-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_remove_newuserregistration_is_certified_educator"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuserregistration",
            name="is_certified_educator",
            field=models.BooleanField(default=False),
        ),
    ]
