# Generated by Django 4.1.3 on 2022-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_remove_newuserregistration_otp_and_more"),
        ("base", "0018_newuserregistration_is_certified_educator"),
    ]

    operations = []
