# Generated by Django 4.1.3 on 2022-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_merge_20221115_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
