# Generated by Django 4.1.3 on 2022-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_interests_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interests",
            name="interest",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
