# Generated by Django 4.1.3 on 2022-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_interests_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserregistration",
            name="interested",
            field=models.ManyToManyField(blank=True, to="base.interests"),
        ),
    ]
