# Generated by Django 4.1.2 on 2022-10-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("educator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educator.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=2000)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                ("bookmark", models.IntegerField(default=0)),
                ("image", models.ImageField(default="", upload_to="note/img")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="educator.topic"
                    ),
                ),
            ],
        ),
    ]
