# Generated by Django 4.1.2 on 2022-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cart_course_cart_total_price_cart_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
