# Generated by Django 4.1.2 on 2022-11-06 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_courses",
            name="price",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(999)]
            ),
        ),
    ]
