<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-09 12:29
=======
# Generated by Django 4.1.2 on 2022-11-09 04:33
>>>>>>> ec44b1891a32618d7ebf392488857e445879ab9f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_courses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="student_mail",
            new_name="email",
        ),
    ]
