# Generated by Django 4.1.2 on 2022-11-08 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cart_courses_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="student",
        ),
        migrations.AddField(
            model_name="cart",
            name="student_mail",
            field=models.EmailField(
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email address",
            ),
        ),
    ]
