# Generated by Django 4.1.2 on 2022-11-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_cart_student_cart_student_mail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart_courses",
            name="student",
        ),
    ]
