# Generated by Django 4.1.2 on 2022-11-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="email",
        ),
    ]
